// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sdlkuseyocwxvgtklfvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkbGt1c2V5b2N3eHZndGtsZnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDQ5ODEsImV4cCI6MjA3NDU4MDk4MX0.iullfKx7CNkUQvL5nI59q3UAkaMWMsNEDSgIFuPlD_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);